---
ID: "0ee0c75d-43fb-4dab-b74e-a559f303d406"
Parent: "6489b458-022d-4973-9e7d-f2ce2c2c01d2"
Template: "f0d16eee-3a05-4e43-a082-795a32b873c0"
Path: /sitecore/system/Settings/Rules/Definitions/Elements/Marketing Automation/Contact has been in Automation campaign
DB: master
SharedFields:
- ID: "ab51c8b2-f0e1-4471-9aae-cc080d774923"
  Hint: Type
  Value: Sitecore.Xdb.MarketingAutomation.Tracking.Conditions.ContactHasBeenInAutomationCampaignCondition, Sitecore.Xdb.MarketingAutomation.Tracking
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Kontakten har været i automatiseringskampagnen
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155358Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "hvor kontakten tidligere har været i automatiseringskampagnen [Definition,AutomationActivity,selectActivityPageType=SelectPlan,specific] og forlod den mellem [ExitStart,DateTime,,start date] og [ExitEnd,DateTime,,end date]"
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Kontakt war in Automatisierungskampagne
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155834Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "wo der Kontakt zuvor in der [Definition,AutomationActivity,selectActivityPageType=SelectPlan,specific] Automationskampagne war und zwischen [ExitStart,DateTime,,Startdatum] und [ExitEnd,DateTime,,Enddatum] vorhanden war"
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170530T042729Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "where the contact has previously been in the [Definition,AutomationActivity,selectActivityPageType=SelectPlan,specific] Automation campaign and exited between [ExitStart,DateTime,,start date] and [ExitEnd,DateTime,,end date]"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: コンタクトはオートメーション キャンペーンに存在します。
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T160250Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "af321234-4eb9-4ef5-9197-65903351939c"
      Hint: Text
      Value: "条件： コンタクトが過去に[Definition,AutomationActivity,selectActivityPageType=SelectPlan,特定の]オートメーション キャンペーンに存在し、[ExitStart,DateTime,,開始日]と[ExitEnd,DateTime,,終了日]の間に終了した場合"
