---
ID: "233901c0-4adf-4bd7-83bd-ee37c9e8e48c"
Parent: "cf9c8a2a-2794-4fea-980a-ef8426f3d6c3"
Template: "cf9c8a2a-2794-4fea-980a-ef8426f3d6c3"
Path: /sitecore/templates/System/Email/Manager Root/__Standard Values
DB: master
SharedFields:
- ID: "0c894aab-962b-4a84-b923-cb24b05e60d2"
  Hint: __Ribbon
  Value: "{144AD540-32DE-46E4-A9B1-E60E8C3D120B}"
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "1b963507-6176-4336-a14d-d5070c3b0286"
  Hint: Base URL
  Value: "http://your.host"
- ID: "54a9031b-154f-4fa6-9350-8979b56f0115"
  Hint: Undelivered Maximum
  Value: 10
- ID: "9135200a-5626-4dd8-ab9d-d665b8c11748"
  Hint: __Never publish
  Type: checkbox
  Value: 0
- ID: "97d7cb7a-1efd-43c0-b39e-8fc28a40356f"
  Hint: Track Message Open
  Type: Checkbox
  Value: 1
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: 
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\EXM Advanced users|pe|+item:create|+item:read|+item:rename|+item:delete|+item:write|^*|pd|+item:create|+item:read|+item:rename|+item:delete|+item:write|^*|ar|sitecore\EXM users|pe|+item:read|^*|pd|+item:read|^*|
- ID: "e0614797-9a63-41c9-aa8a-7a67b490dc5d"
  Hint: Encoding
  Value: "utf-8"
- ID: "ff64b61e-e68d-4be1-bfd1-aae311f4aca1"
  Hint: Embed Images
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20081013T095000
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
