---
ID: "e9d9b933-57a5-4663-a1b9-799383f30d73"
Parent: "3b01233a-b8a2-4d76-bbc6-cf1f8d566d85"
Template: "3505f93a-1bbd-4ea4-bfab-09f44e88a594"
Path: /sitecore/system/Settings/Analytics/Marketing Automation/Activity Types/Delay/Paths/Default
DB: master
SharedFields:
- ID: "ec7ee750-6c26-4def-aa5f-71dcd3a875de"
  Hint: Key
  Value: default
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Standard
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: Standard
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155427Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Default
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: Default
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155909Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: Default
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T125312Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: デフォルト
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: デフォルト
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T160328Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
