---
ID: "3dbd7629-d697-42f0-8693-42fd970fc0bd"
Parent: "fe8d604d-26f6-426d-a3e2-e4edff091b47"
Template: "fe8d604d-26f6-426d-a3e2-e4edff091b47"
Path: /sitecore/templates/System/Email/Message Types/Message Types Container/__Standard Values
DB: master
SharedFields:
- ID: "0c894aab-962b-4a84-b923-cb24b05e60d2"
  Hint: __Ribbon
  Value: "{144AD540-32DE-46E4-A9B1-E60E8C3D120B}"
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{A0C460F4-DBAE-4A5A-8F3A-C4ADFCDACEEA}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20110811T154500
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
