---
ID: "05e606bf-6305-4060-ae27-8f4c83f4848f"
Parent: "3f2d20a6-5554-459a-8377-0db96ff90bc3"
Template: "3f2d20a6-5554-459a-8377-0db96ff90bc3"
Path: /sitecore/templates/System/Email/Messages/ImportFromHtml/__Standard Values
DB: master
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{4BD924C0-3138-4858-8F8E-5608A1115304}" mediapath="/Email Campaign/Thumbnails/import-html" src="~/media/4BD924C0313848588F8E5608A1115304.ashx" />
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155357Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155833Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20121116T150500
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T160249Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
