---
ID: "a401f7df-d86b-4b72-a5e5-c2e8f04ff889"
Parent: "a0ea9681-5c86-43ab-80f7-c522dadf6f12"
Template: "a0ea9681-5c86-43ab-80f7-c522dadf6f12"
Path: /sitecore/templates/System/Email/Messages/Mail Message/__Standard Values
DB: master
SharedFields:
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: "{01FED175-C121-47A5-B65D-36FE7569C232}"
- ID: "af0fe26a-a78b-491d-885c-03d95bc17342"
  Hint: State
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: 
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155418Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T155858Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20081112T100900
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8436a90c-85c0-4f16-8373-393c4c0a82c6"
      Hint: From Name
      Value: 
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "0d844c9c-bd6c-49b8-9475-947da791f268"
      Hint: From Address
      Value: "do-not-reply@yoursite.net"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171219T160318Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
